spring:
  datasource:
    url: jdbc:mysql://database-2.coqkyunwvgqe.ap-northeast-2.rds.amazonaws.com:3306/hackathonA?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 200MB
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      format_sql: true
      ddl-auto: create
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


